type Query {
  posts: [Post!]!
  getPostById(postId: String): Post!
}

type Mutation {
  addPost(input: PostInput): Post!
  updatePost(postId: String, input: PostInput): Post!
  addPostLike(postId: String): Boolean!
  deletePost(postId: String): Boolean!
}

type Subscription {
  newPost: Post
}

type Post {
  id: ID!
  content: String!
  media: String
  sharedPost: Post
  author: User!
  comments: [Comment]
  likes: [User]
  createdAt: Date
}

input PostInput {
  content: String!
  media: String
  sharedPost: String
}