type Mutation {
  register(input: AuthUserInput): AuthResponse
  login(input: AuthUserInput): AuthResponse
}

input AuthUserInput {
  userName: String
  email: String!
  password: String!
}

type AuthResponse {
  accessToken: String!
  refreshToken: String!
}
