type Mutation {
  register(input: RegisterUserInput): AuthResponse
  login(input: SessionInput): AuthResponse
}

input RegisterUserInput {
  userName: String!
  email: String!
  password: String!
  confirmPassword: String!
}

type AuthResponse {
  accessToken: String!
  refreshToken: String!
}
