type Query {
  replies: [Reply!]! @cacheControl(maxAge: 360)
  getReplyById(replyId: String): Post! @cacheControl(maxAge: 360)
}

type Mutation {
  addReply(commentId: String, input: ReplyInput): Reply!
  updateReply(replyId: String, input: ReplyInput): Reply!
  deleteReply(replyId: String): Boolean!
}


type Reply @cacheControl(inheritMaxAge: true) {
  id: ID!
  content: String!
  media: String
  author: User
  commentId: String!
  createdAt: Date
  updatedAt: Date
}

input ReplyInput {
  content: String!
  media: String
}
