type Query {
  replies: [Reply!]!
  getReplyById(replyId: String): Post!
}

type Mutation {
  addReply(commentId: String, input: ReplyInput): Reply!
  updateReply(replyId: String, input: ReplyInput): Reply!
  deleteReply(replyId: String): Boolean!
}

type Reply {
  id: ID!
  content: String!
  media: String
  author: User
  commentId: String!
  createdAt: Date
  updatedAt: Date
}

input ReplyInput {
  content: String!
  media: String
}
