type Query {
  users: [User!]!
  user: User!
}

type Mutation {
  updateUser(userId: String, input: UserInput): User!
  deleteUser(userId: String): Boolean!
}

type User {
  id: ID!
  firstName: String
  lastName: String
  userName: String!
  email: String
  followers: [User]
  tokens: Token
  bio: String
  location: String
  image: String
  cover: String
  isVerified: Boolean
}

input UserInput {
  firstName: String
  lastName: String
  userName: String
  email: String
  bio: String
  location: String
  image: String
  cover: String
}

type Token {
  accessToken: String
  refreshToken: String!
}