type Query {
  users: [User!]!
  user: User!
  userById(userId: String): User!
  followersById(userId: String): [User]
}

type Mutation {
  updateUser(input: UserInput): User!
  deleteUser(userId: String): Boolean!
}

type User {
  id: ID!
  firstName: String
  lastName: String
  userName: String!
  email: String
  followers: [User]
  following: [User]
  refreshToken: String
  bio: String
  location: String
  image: String
  cover: String
  session: String
  activities: [Post]
  isVerified: Boolean
  createdAt: Date
  updatedAt: Date
}

input UserInput {
  firstName: String
  lastName: String
  userName: String
  email: String
  bio: String
  location: String
  image: String
  cover: String
}

