type Query {
  comments: [Comment!]! @cacheControl(maxAge: 360)
  getCommentById(commentId: String): Comment! @cacheControl(maxAge: 360)
}

type Mutation {
  addComment(postId: String, input: CommentInput): Comment!
  updateComment(commentId: String, input: CommentInput): Comment!
  deleteComment(commentId: String): Boolean!
}

type Comment @cacheControl(inheritMaxAge: true) {
  id: ID!
  content: String!
  media: String
  author: User
  postId: String!
  replies: [Reply]
  createdAt: Date
  updatedAt: Date
}

input CommentInput {
  content: String!
  media: String
}